<?php
// admin/export_intervention_audit_pdf.php
require_once '../includes/auth.php';
require_once '../config/constants.php';
require_once '../config/db.php';
require_once '../includes/csv_export_helpers.php';
require_once '../vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

requireRole('admin');
$user = currentUser();
$db = getDB();

// FIXED: Pulling the full lifecycle data required for a compliant audit report
$sql = "
    SELECT 
        asc_case.id, sp.student_number, u.first_name, u.last_name,
        asc_case.trigger_risk_level, asc_case.created_at, asc_case.status,
        f.last_name AS faculty_last, f.first_name AS faculty_first,
        (SELECT MAX(created_at) FROM support_status_history WHERE case_id = asc_case.id AND new_status = 'action_taken') AS notice_sent_at,
        (SELECT MAX(created_at) FROM support_status_history WHERE case_id = asc_case.id AND new_status = 'acknowledged') AS acknowledged_at,
        (SELECT MAX(created_at) FROM support_status_history WHERE case_id = asc_case.id AND new_status IN ('resolved', 'closed')) AS resolved_at
    FROM academic_support_cases asc_case
    JOIN users u ON asc_case.student_id = u.id
    JOIN student_profiles sp ON sp.user_id = u.id
    LEFT JOIN users f ON asc_case.assigned_faculty_id = f.id
    ORDER BY asc_case.created_at DESC
";
$cases = $db->query($sql)->fetchAll(PDO::FETCH_ASSOC);

// Calculate Governance KPIs
$totalCases = count($cases);
$needsReview = 0; $noticeSent = 0; $acknowledged = 0; $closed = 0;
foreach ($cases as $c) {
    if ($c['status'] === 'needs_review') $needsReview++;
    elseif ($c['status'] === 'action_taken') $noticeSent++;
    elseif ($c['status'] === 'acknowledged') $acknowledged++;
    elseif ($c['status'] === 'resolved' || $c['status'] === 'closed') $closed++;
}

$totalIssued = $noticeSent + $acknowledged + $closed;
$ackRate = $totalIssued > 0 ? round((($acknowledged + $closed) / $totalIssued) * 100, 1) . '%' : 'N/A';

$logoPath = '../assets/img/logo_sidebar.png';
$logoBase64 = file_exists($logoPath) ? 'data:image/png;base64,' . base64_encode(file_get_contents($logoPath)) : '';
$logoHtml = $logoBase64 ? '<img src="' . $logoBase64 . '" style="width: 70px; height: auto;" alt="Logo">' : '';

$html = '
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 10px; color: #1e293b; margin: 0; }
        table { width: 100%; border-collapse: collapse; }
        .header-table { border-bottom: 2px solid #1e4dd8; padding-bottom: 10px; margin-bottom: 15px; }
        .meta-table { margin-bottom: 20px; background-color: #f8fafc; font-size: 9px; }
        .meta-table td { padding: 6px 10px; border: 1px solid #e2e8f0; }
        .section-title { font-size: 12px; font-weight: bold; color: #0f172a; margin-bottom: 8px; margin-top: 15px; text-transform: uppercase; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
        
        .kpi-table { margin-bottom: 20px; }
        .kpi-td { border: 1px solid #cbd5e1; text-align: center; padding: 10px 4px; width: 16%; }
        .kpi-val { font-size: 18px; font-weight: bold; margin-bottom: 4px; color: #0f172a; }
        .kpi-lbl { font-size: 8px; color: #64748b; text-transform: uppercase; font-weight: bold; }

        .data-table { font-size: 9px; margin-bottom: 20px; }
        .data-table th { background-color: #f1f5f9; text-align: left; padding: 6px; border-bottom: 2px solid #cbd5e1; color: #334155; }
        .data-table td { padding: 6px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        
        .lifecycle-row { margin-bottom: 2px; }
        .lifecycle-label { display: inline-block; width: 35px; color: #64748b; }
        .lifecycle-date { font-weight: bold; color: #0f172a; }
    </style>
</head>
<body>

    <table class="header-table">
        <tr>
            <td style="width: 80px; vertical-align: middle;">' . $logoHtml . '</td>
            <td style="vertical-align: middle;">
                <h2 style="margin: 0; color: #111827; font-size: 16px; text-transform: uppercase;">Universidad de Manila</h2>
                <p style="margin: 2px 0 0 0; color: #475569; font-size: 11px; font-weight: bold;">UDM-RADAR: Academic Decision Support System</p>
                <p style="margin: 4px 0 0 0; color: #1e4dd8; font-size: 14px; font-weight: bold; text-transform: uppercase;">Intervention Audit Trail</p>
            </td>
            <td style="text-align: right; vertical-align: bottom; width: 150px;">
                <p style="margin: 0; color: #64748b; font-size: 9px;">Date Generated:<br><strong style="color: #111827; font-size: 11px;">' . date('F j, Y') . '</strong></p>
            </td>
        </tr>
    </table>

    <table class="meta-table">
        <tr>
            <td style="width: 20%;"><strong>Generated By:</strong></td>
            <td style="width: 30%;">' . htmlspecialchars($user['first_name'] . ' ' . $user['last_name']) . ' (Admin)</td>
            <td style="width: 20%;"><strong>Report Scope:</strong></td>
            <td style="width: 30%;">Institution-Wide (All Time)</td>
        </tr>
    </table>

    <div class="section-title">Support Intervention Governance Summary</div>
    <table class="kpi-table">
        <tr>
            <td class="kpi-td"><div class="kpi-val">' . $totalCases . '</div><div class="kpi-lbl">Total Support Cases</div></td>
            <td class="kpi-td"><div class="kpi-val" style="color: #d97706;">' . $needsReview . '</div><div class="kpi-lbl">Awaiting Faculty Review</div></td>
            <td class="kpi-td"><div class="kpi-val" style="color: #1e4dd8;">' . $noticeSent . '</div><div class="kpi-lbl">Awaiting Acknowledgment</div></td>
            <td class="kpi-td"><div class="kpi-val" style="color: #059669;">' . $acknowledged . '</div><div class="kpi-lbl">Acknowledged by Student</div></td>
            <td class="kpi-td"><div class="kpi-val" style="color: #64748b;">' . $closed . '</div><div class="kpi-lbl">Closed / Resolved</div></td>
            <td class="kpi-td"><div class="kpi-val" style="color: #0f172a;">' . $ackRate . '</div><div class="kpi-lbl">Acknowledgment Rate</div></td>
        </tr>
    </table>

    <div class="section-title">Support Case Ledger (Top 50 Most Recent)</div>
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 15%;">Date Logged</th>
                <th style="width: 25%;">Student</th>
                <th style="width: 15%;">Trigger Risk Level</th>
                <th style="width: 20%;">Reviewing Faculty</th>
                <th style="width: 25%;">Status & Lifecycle</th>
            </tr>
        </thead>
        <tbody>';

$displayCases = array_slice($cases, 0, 50);
if (empty($displayCases)) {
    $html .= '<tr><td colspan="5" style="text-align:center; color:#94a3b8;">No support cases recorded.</td></tr>';
}

function fmtDate($dateStr) { return $dateStr ? date('M j, Y', strtotime($dateStr)) : '—'; }

foreach ($displayCases as $c) {
    $statusMap = ['needs_review' => 'Awaiting Review', 'action_taken' => 'Notice Sent', 'acknowledged' => 'Acknowledged', 'resolved' => 'Closed', 'closed' => 'Closed'];
    $statusColor = match($c['status']) { 'needs_review' => '#d97706', 'action_taken' => '#1e4dd8', 'acknowledged' => '#059669', default => '#64748b' };
    
    $facultyName = $c['faculty_last'] ? htmlspecialchars($c['faculty_last'] . ', ' . $c['faculty_first']) : '<span style="color:#94a3b8;">Unassigned</span>';

    // Build Lifecycle UI
    $lifecycleHtml = '<div style="color: ' . $statusColor . '; font-weight: bold; margin-bottom: 6px;">' . ($statusMap[$c['status']] ?? 'Unknown') . '</div>';
    
    if ($c['status'] !== 'needs_review') {
        $lifecycleHtml .= '<div style="font-size: 8px;">';
        $lifecycleHtml .= '<div class="lifecycle-row"><span class="lifecycle-label">Notice:</span> <span class="lifecycle-date">' . fmtDate($c['notice_sent_at']) . '</span></div>';
        $lifecycleHtml .= '<div class="lifecycle-row"><span class="lifecycle-label">Ack:</span> <span class="lifecycle-date">' . fmtDate($c['acknowledged_at']) . '</span></div>';
        if ($c['resolved_at']) {
            $lifecycleHtml .= '<div class="lifecycle-row"><span class="lifecycle-label">Closed:</span> <span class="lifecycle-date">' . fmtDate($c['resolved_at']) . '</span></div>';
        }
        $lifecycleHtml .= '</div>';
    }

    $html .= '<tr>
        <td>' . date('M j, Y', strtotime($c['created_at'])) . '</td>
        <td><strong>' . htmlspecialchars($c['last_name'] . ', ' . $c['first_name']) . '</strong><br><span style="color:#64748b; font-size:8px;">' . htmlspecialchars($c['student_number']) . '</span></td>
        <td><span style="font-weight: bold; color: #dc2626;">' . htmlspecialchars($c['trigger_risk_level']) . ' Risk</span></td>
        <td>' . $facultyName . '</td>
        <td>' . $lifecycleHtml . '</td>
    </tr>';
}

$html .= '
        </tbody>
    </table>

    <div style="margin-top: 15px; border-top: 1px solid #cbd5e1; padding-top: 8px; text-align: center; color: #64748b; font-size: 8px; position: absolute; bottom: 10px; width: 100%;">
        <strong>Governance Note:</strong> Student acknowledgment confirms receipt of the Academic Support Notice. It does not represent agreement with the prediction, risk classification, or recommended action.<br>
        <strong>Confidentiality Notice:</strong> This report supports academic review and does not represent an automatic disciplinary decision. Contains sensitive student data.
    </div>

</body>
</html>';

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', true);
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

$canvas = $dompdf->getCanvas();
$font = $dompdf->getFontMetrics()->get_font("sans-serif", "normal");
$canvas->page_text(520, 810, "Page {PAGE_NUM} of {PAGE_COUNT}", $font, 9, array(0.4, 0.4, 0.4));

logExportAudit($db, $user['id'], 'Intervention Audit Trail', 'PDF', ['scope' => 'Top 50'], count($displayCases));

$dompdf->stream("UDM-RADAR_Intervention_Audit_Trail_" . date('Ymd_Hi') . ".pdf", ["Attachment" => true]);
exit;