<?php
// includes/csv_export_helpers.php

function sanitize_csv_field(mixed $val): string {
    if ($val === null) {
        return '';
    }

    $str = (string) $val;
    $checkValue = ltrim($str, " \t\r\n");

    if ($checkValue !== '' && in_array($checkValue[0], ['=', '+', '-', '@'], true)) {
        return "'" . $str;
    }

    return $str;
}

function startCsvDownload(string $baseFilename) {
    $filename = $baseFilename . "_" . date('Y-m-d_Hi') . ".csv";
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    return fopen('php://output', 'w');
}

function writeCsvMetadata($output, array $user, string $reportTitle, array $filters, int $totalRecords): void {
    fputcsv($output, ['=== UDM-RADAR: ' . strtoupper($reportTitle) . ' ===']);
    fputcsv($output, ['Generated By:', sanitize_csv_field($user['first_name'] . ' ' . $user['last_name'] . ' (' . ucfirst($user['role']) . ')')]);
    fputcsv($output, ['Timestamp:', sanitize_csv_field(date('F j, Y, g:i A'))]);
    
    $filterStrs = [];
    foreach ($filters as $k => $v) {
        if ($v !== '') $filterStrs[] = ucfirst($k) . ': ' . $v;
    }
    fputcsv($output, ['Applied Filters:', sanitize_csv_field(!empty($filterStrs) ? implode(' | ', $filterStrs) : 'None (All)')]);
    fputcsv($output, ['Total Records:', $totalRecords]);
    fputcsv($output, []); 
}

function logExportAudit(PDO $db, int $userId, string $reportType, string $format, array $filtersArray, int $rowCount): void {
    try {
        $stmt = $db->prepare("
            INSERT INTO export_audit_logs (user_id, report_type, format, filters_json, row_count, success) 
            VALUES (?, ?, ?, ?, ?, 1)
        ");
        $stmt->execute([
            $userId, 
            $reportType, 
            strtoupper($format), 
            json_encode($filtersArray), 
            $rowCount
        ]);
    } catch (Throwable $e) {
        error_log('Export audit logging failed: ' . $e->getMessage());
    }
}